SSID = 'SENSITIVE INFO'
AUTH_TOKEN = '71f96ba0e8cd6c92c598e98cfe9fdf93'
FROM_NUMBER = 'SENSITIVE INFO'
TO_NUMBER = 'SENSITIVE INFO'
API_KEY = 'SENSITIVE INFO'
DEVICE_ID = 'SENSITIVE INFO'
FRAME_SIZE = 10
MUL_FACTOR = 6
