MAILGUN_API_KEY='SENSITIVE INFO'
SANDBOX_URL='SENSITIVE INFO'
SENDER_EMAIL='SENSITIVE INFO'
RECIPIENT_EMAIL='divyanshugadhwal@gmail.com'
API_KEY='SENSITIVE INFO'
DEVICE_ID='SENSITIVE INFO'
FRAME_SIZE = 10
MUL_FACTOR = 6
